### ISSUE TITLE
Invalid S7 Connection crashes app

### ISSUE THREAD

**Issue by grigals** [AMRC-FactoryPlus/acs-edge#37]
When an S7 connection is wrong, it crashes the whole app.

Connection failure not handled well.

Logs:
```
DEBUG [2023-11-23T12:57:29.719Z] app.ts:57:5 --> Attempting to fetch config...
DEBUG [2023-11-23T12:57:30.144Z] app.ts:65:5 --> Config fetched.
DEBUG [2023-11-23T12:57:30.208Z] translator.ts:133:13 --> Created Sparkplug node "..." in group "...".
DEBUG [2023-11-23T12:57:30.209Z] translator.ts:135:13 --> Building up connections and devices...
Error: Unhandled error. (undefined)
    at new NodeError (node:internal/errors:405:5)
    at S7Connection.emit (node:events:506:17)
    at S7Endpoint.<anonymous> (file:///usr/lib/devices/S7.ts:57:18)
    at S7Endpoint.emit (node:events:529:35)
    at S7Endpoint._onTransportError (/usr/app/node_modules/@st-one-io/nodes7/src/s7endpoint.js:351:14)
    at /usr/app/node_modules/@st-one-io/nodes7/src/s7endpoint.js:190:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by grigals** [comment]
#38
